name: Deploy Backend with FTP
on:
  push:
    branches: [ "main" ]
jobs:
  deploy:
    name: Upload backend to FTP
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Sync backend to FTP
        uses: SamKirkland/FTP-Deploy-Action@4.3.0
        with:
          server: ${{ secrets.FTP_HOST_BACK }}
          port: ${{ secrets.FTP_PORT_BACK }}
          username: ${{ secrets.FTP_USERNAME_BACK }}
          password: ${{ secrets.FTP_PASSWORD_BACK }}
          local-dir: lab01/lab01/bookstore/
          server-dir: ${{ secrets.FTP_REMOTE_PATH_BACK }}
